# Generated by Django 5.0.7 on 2024-07-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('code_postal', models.SmallIntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('civilite', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('telephone_mobile', models.CharField(max_length=20)),
                ('telephone_fixe', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Incoterms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('definition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barre', models.CharField(max_length=13)),
                ('code_article', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('gamme', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dim', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('mention', models.CharField(max_length=200)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionStock.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='EtatStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_etat', models.DateField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionStock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='EntreeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_entree', models.DateField()),
                ('numero_commande', models.CharField(max_length=100)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionStock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='SortieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_sortie', models.DateField()),
                ('numero_commande_client', models.CharField(max_length=100)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionStock.produit')),
            ],
        ),
    ]
